language: node_js
sudo: false
addons:
  code_climate:
    repo_token: f642afb4fb96a9cd320aeaf3ccf6b66e03d85c5830500dfeaca2f26bf1811672
node_js:
- '4'
- '6'
cache:
  directories:
  - node_modules
script:
- npm run lint
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive
- codecov
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
after_success:
- bash <(curl -s https://codecov.io/bash)
